2024-03-06 10:56:52.396 | INFO     | core.utils.logging_manager:log_information:46 - -
2024-03-06 10:56:58.492 | ERROR    | _pytest.python:pytest_pyfunc_call:194 - An error has been caught in function 'pytest_pyfunc_call', process 'MainProcess' (13976), thread 'MainThread' (11420):
Traceback (most recent call last):

  File "F:\Program Files\PyCharm Community Edition 2023.2.1\plugins\python-ce\helpers\pycharm\_jb_pytest_runner.py", line 60, in <module>
    sys.exit(pytest.main(args, plugins_to_load + [Plugin]))
    │   │    │      │    │     │                  └ <class '__main__.Plugin'>
    │   │    │      │    │     └ [<module 'teamcity.pytest_plugin' from 'F:\\Program Files\\PyCharm Community Edition 2023.2.1\\plugins\\python-ce\\helpers\\p...
    │   │    │      │    └ ['test_win.py::test_desktop', '--no-header', '--no-summary', '-q']
    │   │    │      └ <function main at 0x000001614AED7600>
    │   │    └ <module 'pytest' from 'C:\\Repos\\MyGit\\PythonTestFramework\\venv\\Lib\\site-packages\\pytest\\__init__.py'>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

  File "C:\Repos\MyGit\PythonTestFramework\venv\Lib\site-packages\_pytest\config\__init__.py", line 175, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
         │     │                │      │    └ <HookCaller 'pytest_cmdline_main'>
         │     │                │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x000001614B2A3B90>
         │     │                └ <_pytest.config.Config object at 0x000001614B2A3990>
         │     └ <enum 'ExitCode'>
         └ typing.Union
  File "C:\Repos\MyGit\PythonTestFramework\venv\Lib\site-packages\pluggy\_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           │    │         │    │     │    │                  │       └ True
           │    │         │    │     │    │                  └ {'config': <_pytest.config.Config object at 0x000001614B2A3990>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_cmdline_main'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_cmdline_main'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_cmdline_main'>
  File "C:\Repos\MyGit\PythonTestFramework\venv\Lib\site-packages\pluggy\_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'config': <_pytest.config.Config object at 0x000001614B2A3990>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from 'C:\\Repos\\MyGit\\PythonTestFramework\\venv\\Lib\\site-pac...
           │    │               └ 'pytest_cmdline_main'
           │    └ <function _multicall at 0x000001614A73C680>
           └ <_pytest.config.PytestPluginManager object at 0x000001614B200350>
  File "C:\Repos\MyGit\PythonTestFramework\venv\Lib\site-packages\pluggy\_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<_pytest.config.Config object at 0x000001614B2A3990>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from 'C:\\Repos\\MyGit\\PythonTestFramework\\venv\\Lib\\site-pack...
  File "C:\Repos\MyGit\PythonTestFramework\venv\Lib\site-packages\_pytest\main.py", line 320, in pytest_cmdline_main
    return wrap_session(config, _main)
           │            │       └ <function _main at 0x000001614AF9E480>
           │            └ <_pytest.config.Config object at 0x000001614B2A3990>
           └ <function wrap_session at 0x000001614AF9E3E0>
  File "C:\Repos\MyGit\PythonTestFramework\venv\Lib\site-packages\_pytest\main.py", line 273, in wrap_session
    session.exitstatus = doit(config, session) or 0
    │       │            │    │       └ <Session  exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=1>
    │       │            │    └ <_pytest.config.Config object at 0x000001614B2A3990>
    │       │            └ <function _main at 0x000001614AF9E480>
    │       └ <ExitCode.OK: 0>
    └ <Session  exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=1>
  File "C:\Repos\MyGit\PythonTestFramework\venv\Lib\site-packages\_pytest\main.py", line 327, in _main
    config.hook.pytest_runtestloop(session=session)
    │      │    │                          └ <Session  exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=1>
    │      │    └ <HookCaller 'pytest_runtestloop'>
    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x000001614B2A3B90>
    └ <_pytest.config.Config object at 0x000001614B2A3990>
  File "C:\Repos\MyGit\PythonTestFramework\venv\Lib\site-packages\pluggy\_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           │    │         │    │     │    │                  │       └ True
           │    │         │    │     │    │                  └ {'session': <Session  exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=1>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_runtestloop'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_runtestloop'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_runtestloop'>
  File "C:\Repos\MyGit\PythonTestFramework\venv\Lib\site-packages\pluggy\_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'session': <Session  exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=1>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from 'C:\\Repos\\MyGit\\PythonTestFramework\\venv\\Lib\\site-pac...
           │    │               └ 'pytest_runtestloop'
           │    └ <function _multicall at 0x000001614A73C680>
           └ <_pytest.config.PytestPluginManager object at 0x000001614B200350>
  File "C:\Repos\MyGit\PythonTestFramework\venv\Lib\site-packages\pluggy\_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Session  exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=1>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from 'C:\\Repos\\MyGit\\PythonTestFramework\\venv\\Lib\\site-pack...
  File "C:\Repos\MyGit\PythonTestFramework\venv\Lib\site-packages\_pytest\main.py", line 352, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    │    │                                        │              └ None
    │    │                                        └ <Function test_desktop[Microsoft.WindowsCalculator_8wekyb3d8bbwe!App]>
    │    └ <member 'config' of 'Node' objects>
    └ <Function test_desktop[Microsoft.WindowsCalculator_8wekyb3d8bbwe!App]>
  File "C:\Repos\MyGit\PythonTestFramework\venv\Lib\site-packages\pluggy\_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           │    │         │    │     │    │                  │       └ True
           │    │         │    │     │    │                  └ {'item': <Function test_desktop[Microsoft.WindowsCalculator_8wekyb3d8bbwe!App]>, 'nextitem': None}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_runtest_protocol'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_runtest_protocol'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_runtest_protocol'>
  File "C:\Repos\MyGit\PythonTestFramework\venv\Lib\site-packages\pluggy\_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'item': <Function test_desktop[Microsoft.WindowsCalculator_8wekyb3d8bbwe!App]>, 'nextitem': None}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from 'C:\\Repos\\MyGit\\PythonTestFramework\\venv\\Lib\\site...
           │    │               └ 'pytest_runtest_protocol'
           │    └ <function _multicall at 0x000001614A73C680>
           └ <_pytest.config.PytestPluginManager object at 0x000001614B200350>
  File "C:\Repos\MyGit\PythonTestFramework\venv\Lib\site-packages\pluggy\_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_desktop[Microsoft.WindowsCalculator_8wekyb3d8bbwe!App]>, None]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from 'C:\\Repos\\MyGit\\PythonTestFramework\\venv\\Lib\\site-...
  File "C:\Repos\MyGit\PythonTestFramework\venv\Lib\site-packages\_pytest\runner.py", line 115, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
    │               │              └ None
    │               └ <Function test_desktop[Microsoft.WindowsCalculator_8wekyb3d8bbwe!App]>
    └ <function runtestprotocol at 0x000001614AF9D580>
  File "C:\Repos\MyGit\PythonTestFramework\venv\Lib\site-packages\_pytest\runner.py", line 134, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
    │       │      │               │             └ True
    │       │      │               └ <Function test_desktop[Microsoft.WindowsCalculator_8wekyb3d8bbwe!App]>
    │       │      └ <function call_and_report at 0x000001614AF9D9E0>
    │       └ <method 'append' of 'list' objects>
    └ [<TestReport 'test_win.py::test_desktop[Microsoft.WindowsCalculator_8wekyb3d8bbwe!App]' when='setup' outcome='passed'>]
  File "C:\Repos\MyGit\PythonTestFramework\venv\Lib\site-packages\_pytest\runner.py", line 223, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
           │                 │     │       └ {}
           │                 │     └ 'call'
           │                 └ <Function test_desktop[Microsoft.WindowsCalculator_8wekyb3d8bbwe!App]>
           └ <function call_runtest_hook at 0x000001614AF9DB20>
  File "C:\Repos\MyGit\PythonTestFramework\venv\Lib\site-packages\_pytest\runner.py", line 262, in call_runtest_hook
    return CallInfo.from_call(
           │        └ <classmethod(<function CallInfo.from_call at 0x000001614AF9DDA0>)>
           └ <class '_pytest.runner.CallInfo'>
  File "C:\Repos\MyGit\PythonTestFramework\venv\Lib\site-packages\_pytest\runner.py", line 342, in from_call
    result: Optional[TResult] = func()
            │        │          └ <function call_runtest_hook.<locals>.<lambda> at 0x000001614D9E7060>
            │        └ +TResult
            └ typing.Optional
  File "C:\Repos\MyGit\PythonTestFramework\venv\Lib\site-packages\_pytest\runner.py", line 263, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            │          │       └ {}
            │          └ <Function test_desktop[Microsoft.WindowsCalculator_8wekyb3d8bbwe!App]>
            └ <HookCaller 'pytest_runtest_call'>
  File "C:\Repos\MyGit\PythonTestFramework\venv\Lib\site-packages\pluggy\_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           │    │         │    │     │    │                  │       └ False
           │    │         │    │     │    │                  └ {'item': <Function test_desktop[Microsoft.WindowsCalculator_8wekyb3d8bbwe!App]>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_runtest_call'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_runtest_call'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_runtest_call'>
  File "C:\Repos\MyGit\PythonTestFramework\venv\Lib\site-packages\pluggy\_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ False
           │    │               │          │        └ {'item': <Function test_desktop[Microsoft.WindowsCalculator_8wekyb3d8bbwe!App]>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from 'C:\\Repos\\MyGit\\PythonTestFramework\\venv\\Lib\\site...
           │    │               └ 'pytest_runtest_call'
           │    └ <function _multicall at 0x000001614A73C680>
           └ <_pytest.config.PytestPluginManager object at 0x000001614B200350>
  File "C:\Repos\MyGit\PythonTestFramework\venv\Lib\site-packages\pluggy\_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_desktop[Microsoft.WindowsCalculator_8wekyb3d8bbwe!App]>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from 'C:\\Repos\\MyGit\\PythonTestFramework\\venv\\Lib\\site-...
  File "C:\Repos\MyGit\PythonTestFramework\venv\Lib\site-packages\_pytest\runner.py", line 170, in pytest_runtest_call
    item.runtest()
    │    └ <function Function.runtest at 0x000001614B0A5620>
    └ <Function test_desktop[Microsoft.WindowsCalculator_8wekyb3d8bbwe!App]>
  File "C:\Repos\MyGit\PythonTestFramework\venv\Lib\site-packages\_pytest\python.py", line 1831, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
    │    │                                   └ <Function test_desktop[Microsoft.WindowsCalculator_8wekyb3d8bbwe!App]>
    │    └ <property object at 0x000001614AEFC180>
    └ <Function test_desktop[Microsoft.WindowsCalculator_8wekyb3d8bbwe!App]>
  File "C:\Repos\MyGit\PythonTestFramework\venv\Lib\site-packages\pluggy\_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           │    │         │    │     │    │                  │       └ True
           │    │         │    │     │    │                  └ {'pyfuncitem': <Function test_desktop[Microsoft.WindowsCalculator_8wekyb3d8bbwe!App]>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_pyfunc_call'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_pyfunc_call'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_pyfunc_call'>
  File "C:\Repos\MyGit\PythonTestFramework\venv\Lib\site-packages\pluggy\_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'pyfuncitem': <Function test_desktop[Microsoft.WindowsCalculator_8wekyb3d8bbwe!App]>}
           │    │               │          └ [<HookImpl plugin_name='python', plugin=<module '_pytest.python' from 'C:\\Repos\\MyGit\\PythonTestFramework\\venv\\Lib\\site...
           │    │               └ 'pytest_pyfunc_call'
           │    └ <function _multicall at 0x000001614A73C680>
           └ <_pytest.config.PytestPluginManager object at 0x000001614B200350>
  File "C:\Repos\MyGit\PythonTestFramework\venv\Lib\site-packages\pluggy\_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_desktop[Microsoft.WindowsCalculator_8wekyb3d8bbwe!App]>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='python', plugin=<module '_pytest.python' from 'C:\\Repos\\MyGit\\PythonTestFramework\\venv\\Lib\\site-...
> File "C:\Repos\MyGit\PythonTestFramework\venv\Lib\site-packages\_pytest\python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
             │              └ {'desktop_driver': <appium.webdriver.webdriver.WebDriver (session="b06a8fc3-e6eb-4a48-8a13-cfe409d074f7")>}
             └ <function test_desktop at 0x000001614B3C9BC0>

  File "C:\Repos\MyGit\PythonTestFramework\tests\desktop\test_win.py", line 17, in test_desktop
    desktop_driver.find_element(AppiumBy.ACCESSIBILITY_I, 'num1Button').click()
    │              │            └ <class 'appium.webdriver.common.appiumby.AppiumBy'>
    │              └ <function WebDriver.find_element at 0x000001614D75DDA0>
    └ <appium.webdriver.webdriver.WebDriver (session="b06a8fc3-e6eb-4a48-8a13-cfe409d074f7")>

AttributeError: type object 'AppiumBy' has no attribute 'ACCESSIBILITY_I'
